-- ALIXMAX Supabase setup
-- Run this once in Supabase > SQL Editor.
-- NOTE: The current frontend uses a client-side group gate. For real production security,
-- move owner/member authentication to Supabase Auth + server-side policies.

create extension if not exists pgcrypto;

create table if not exists public.posts (
  id text primary key,
  title text not null,
  type text not null,
  description text not null,
  image text,
  created_at timestamptz not null default now()
);

create table if not exists public.comments (
  id text primary key,
  name text not null,
  phone text not null,
  text text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.sponsors (
  id text primary key,
  name text not null,
  phone text not null,
  link text,
  description text not null,
  price numeric not null default 0,
  image text,
  discount_code text default 'alixmax503',
  discount_percent integer default 30,
  status text default 'pending',
  created_at timestamptz not null default now()
);

create table if not exists public.market_items (
  id text primary key,
  seller text not null,
  phone text not null,
  title text not null,
  category text not null,
  price numeric not null default 0,
  description text not null,
  image text,
  sold boolean not null default false,
  buyer jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.chat_messages (
  id text primary key,
  name text not null,
  text text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.wallet_state (
  id integer primary key,
  balance numeric not null default 0,
  transactions jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now()
);

insert into public.wallet_state(id,balance,transactions)
values(1,0,'[]'::jsonb)
on conflict (id) do nothing;

create table if not exists public.site_visits (
  id bigint generated by default as identity primary key,
  visitor_id text,
  created_at timestamptz not null default now()
);

create table if not exists public.group_members (
  id text primary key,
  username text not null unique,
  display_name text not null,
  password_hash text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.group_messages (
  id text primary key,
  room text not null default 'chat',
  member_id text,
  username text not null,
  display_name text not null,
  text text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.group_announcements (
  id text primary key,
  title text not null,
  body text not null,
  scheduled_at timestamptz,
  created_at timestamptz not null default now()
);

-- Enable RLS
alter table public.posts enable row level security;
alter table public.comments enable row level security;
alter table public.sponsors enable row level security;
alter table public.market_items enable row level security;
alter table public.chat_messages enable row level security;
alter table public.wallet_state enable row level security;
alter table public.site_visits enable row level security;
alter table public.group_members enable row level security;
alter table public.group_messages enable row level security;
alter table public.group_announcements enable row level security;

-- Public content: read + insert
drop policy if exists "public read posts" on public.posts;
create policy "public read posts" on public.posts for select to anon, authenticated using (true);
drop policy if exists "public insert posts" on public.posts;
create policy "public insert posts" on public.posts for insert to anon, authenticated with check (true);
drop policy if exists "public update posts" on public.posts;
create policy "public update posts" on public.posts for update to anon, authenticated using (true) with check (true);

drop policy if exists "public read comments" on public.comments;
create policy "public read comments" on public.comments for select to anon, authenticated using (true);
drop policy if exists "public insert comments" on public.comments;
create policy "public insert comments" on public.comments for insert to anon, authenticated with check (true);

drop policy if exists "public read sponsors" on public.sponsors;
create policy "public read sponsors" on public.sponsors for select to anon, authenticated using (true);
drop policy if exists "public insert sponsors" on public.sponsors;
create policy "public insert sponsors" on public.sponsors for insert to anon, authenticated with check (true);
drop policy if exists "public update sponsors" on public.sponsors;
create policy "public update sponsors" on public.sponsors for update to anon, authenticated using (true) with check (true);

drop policy if exists "public read market" on public.market_items;
create policy "public read market" on public.market_items for select to anon, authenticated using (true);
drop policy if exists "public insert market" on public.market_items;
create policy "public insert market" on public.market_items for insert to anon, authenticated with check (true);
drop policy if exists "public update market" on public.market_items;
create policy "public update market" on public.market_items for update to anon, authenticated using (true) with check (true);

drop policy if exists "public read chat" on public.chat_messages;
create policy "public read chat" on public.chat_messages for select to anon, authenticated using (true);
drop policy if exists "public insert chat" on public.chat_messages;
create policy "public insert chat" on public.chat_messages for insert to anon, authenticated with check (true);

-- Wallet: frontend currently treats it as the ALIXMAX owner wallet.
drop policy if exists "public read wallet" on public.wallet_state;
create policy "public read wallet" on public.wallet_state for select to anon, authenticated using (true);
drop policy if exists "public upsert wallet" on public.wallet_state;
create policy "public upsert wallet" on public.wallet_state for insert to anon, authenticated with check (true);
create policy "public update wallet" on public.wallet_state for update to anon, authenticated using (true) with check (true);

-- Visits
drop policy if exists "public insert visits" on public.site_visits;
create policy "public insert visits" on public.site_visits for insert to anon, authenticated with check (true);
drop policy if exists "public read visits" on public.site_visits;
create policy "public read visits" on public.site_visits for select to anon, authenticated using (true);

-- Group. These policies make the browser implementation work without Supabase Auth.
-- Do NOT treat them as production-grade access control.
drop policy if exists "public read group members" on public.group_members;
create policy "public read group members" on public.group_members for select to anon, authenticated using (true);
drop policy if exists "public insert group members" on public.group_members;
create policy "public insert group members" on public.group_members for insert to anon, authenticated with check (true);
drop policy if exists "public update group members" on public.group_members;
create policy "public update group members" on public.group_members for update to anon, authenticated using (true) with check (true);

drop policy if exists "public read group messages" on public.group_messages;
create policy "public read group messages" on public.group_messages for select to anon, authenticated using (true);
drop policy if exists "public insert group messages" on public.group_messages;
create policy "public insert group messages" on public.group_messages for insert to anon, authenticated with check (true);

drop policy if exists "public read announcements" on public.group_announcements;
create policy "public read announcements" on public.group_announcements for select to anon, authenticated using (true);
drop policy if exists "public insert announcements" on public.group_announcements;
create policy "public insert announcements" on public.group_announcements for insert to anon, authenticated with check (true);

-- Realtime
alter publication supabase_realtime add table public.group_messages;
alter publication supabase_realtime add table public.group_announcements;
